from datetime import datetime
from typing import Any, Dict
from xml.sax.saxutils import escape

from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, LongTable
from reportlab.lib import colors


def add_footer(canvas, doc):
	"""Canvas callback to draw a clean footer on all pages."""
	canvas.saveState()
	canvas.setFont('Helvetica', 8)
	canvas.setFillColor(colors.HexColor("#4f5b70"))
	
	# Draw divider line above footer
	canvas.setStrokeColor(colors.HexColor("#eadcc8"))
	canvas.setLineWidth(0.5)
	canvas.line(54, 45, 558, 45)
	
	# Draw footer labels
	canvas.drawString(54, 30, "Generated by ScrapeX")
	canvas.drawRightString(558, 30, f"Page {doc.page}")
	canvas.restoreState()


def export_to_pdf(data: Dict[str, Any], filename: str = "report.pdf") -> None:
	"""Generate a clean, professional PDF report from scraped website data.

	Args:
		data: Scraped data dictionary containing values such as title, url,
			clean_text, and headings.
		filename: Output PDF filename.
	"""
	# Document layout configuration (margins set to 54pt / 0.75 in)
	doc = SimpleDocTemplate(
		filename,
		leftMargin=54,
		rightMargin=54,
		topMargin=54,
		bottomMargin=54
	)
	story = []

	# Raw data extraction
	title = str(data.get("title") or "No Title")
	url = str(data.get("url") or "")
	clean_text = str(data.get("clean_text") or "No content available")

	raw_headings = data.get("headings")
	if isinstance(raw_headings, list):
		headings = [str(item) for item in raw_headings if item]
	else:
		headings = []

	raw_tables = data.get("tables")
	if isinstance(raw_tables, list):
		tables = [item for item in raw_tables if isinstance(item, list) and item]
	else:
		tables = []

	# Style Definitions
	styles = getSampleStyleSheet()
	
	# Cohesive design palette variables
	primary_color = colors.HexColor("#0f9d8b")   # Teal
	secondary_color = colors.HexColor("#2f71d8") # Blue
	text_color = colors.HexColor("#1a2333")      # Ink
	muted_color = colors.HexColor("#4f5b70")     # Muted Ink
	bg_color = colors.HexColor("#fffdf7")        # Sand / Paper background
	line_color = colors.HexColor("#eadcc8")      # Border sand-gold line

	title_style = ParagraphStyle(
		'ReportTitle',
		parent=styles['Heading1'],
		fontName='Helvetica-Bold',
		fontSize=22,
		leading=26,
		textColor=primary_color,
		spaceAfter=6
	)
	
	meta_label_style = ParagraphStyle(
		'MetaLabel',
		parent=styles['Normal'],
		fontName='Helvetica-Bold',
		fontSize=9,
		leading=13,
		textColor=text_color
	)

	meta_value_style = ParagraphStyle(
		'MetaValue',
		parent=styles['Normal'],
		fontName='Helvetica',
		fontSize=9,
		leading=13,
		textColor=muted_color
	)

	section_heading_style = ParagraphStyle(
		'SectionHeading',
		parent=styles['Heading2'],
		fontName='Helvetica-Bold',
		fontSize=13,
		leading=17,
		textColor=secondary_color,
		spaceBefore=14,
		spaceAfter=6,
		keepWithNext=True
	)

	body_style = ParagraphStyle(
		'ReportBodyText',
		parent=styles['Normal'],
		fontName='Helvetica',
		fontSize=9,
		leading=14,
		textColor=text_color,
		spaceAfter=10
	)

	bullet_style = ParagraphStyle(
		'ReportBulletText',
		parent=styles['Normal'],
		fontName='Helvetica',
		fontSize=9,
		leading=13,
		textColor=text_color,
		leftIndent=15,
		firstLineIndent=-10,
		spaceAfter=4
	)

	cell_style = ParagraphStyle(
		'TableCellStyle',
		parent=styles['Normal'],
		fontSize=8,
		leading=10,
		textColor=text_color
	)

	header_cell_style = ParagraphStyle(
		'TableHeaderStyle',
		parent=styles['Normal'],
		fontSize=8,
		leading=10,
		textColor=colors.whitesmoke,
		fontName='Helvetica-Bold'
	)

	# ----------------------------------------------------
	# 1. Cover Header
	# ----------------------------------------------------
	story.append(Paragraph("ScrapeX Web Scraper Report", title_style))
	story.append(Spacer(1, 10))

	timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
	meta_data = [
		[Paragraph("Website Title:", meta_label_style), Paragraph(escape(title), meta_value_style)],
		[Paragraph("Source URL:", meta_label_style), Paragraph(escape(url), meta_value_style)],
		[Paragraph("Generated At:", meta_label_style), Paragraph(timestamp_str, meta_value_style)]
	]
	
	# Total printable width is 504 (612 page width - 108 margins)
	meta_table = Table(meta_data, colWidths=[110, 394])
	meta_table.setStyle(TableStyle([
		('VALIGN', (0, 0), (-1, -1), 'TOP'),
		('BOTTOMPADDING', (0, 0), (-1, -1), 4),
		('TOPPADDING', (0, 0), (-1, -1), 4),
	]))
	story.append(meta_table)
	
	# Divider line separating header from summary
	divider = Table([[""]], colWidths=[504])
	divider.setStyle(TableStyle([
		('LINEBELOW', (0, 0), (-1, -1), 1, primary_color),
		('BOTTOMPADDING', (0, 0), (-1, -1), 8),
		('TOPPADDING', (0, 0), (-1, -1), 8),
	]))
	story.append(divider)
	story.append(Spacer(1, 15))

	# ----------------------------------------------------
	# 2. Summary
	# ----------------------------------------------------
	story.append(Paragraph("Summary Statistics", section_heading_style))
	story.append(Spacer(1, 6))

	summary_data = [
		[Paragraph("<b>Statistic</b>", meta_label_style), Paragraph("<b>Value</b>", meta_label_style)],
		[Paragraph("Content Length (characters)", body_style), Paragraph(str(len(clean_text)), body_style)],
		[Paragraph("Heading Count", body_style), Paragraph(str(len(headings)), body_style)],
		[Paragraph("Paragraph Count", body_style), Paragraph(str(len(data.get("paragraphs") or [])), body_style)],
		[Paragraph("Link Count", body_style), Paragraph(str(len(data.get("links") or [])), body_style)],
		[Paragraph("Table Count", body_style), Paragraph(str(len(tables)), body_style)]
	]
	summary_table = Table(summary_data, colWidths=[252, 252])
	summary_table.setStyle(TableStyle([
		('BACKGROUND', (0, 0), (-1, 0), line_color),
		('BOTTOMPADDING', (0, 0), (-1, -1), 6),
		('TOPPADDING', (0, 0), (-1, -1), 6),
		('LEFTPADDING', (0, 0), (-1, -1), 8),
		('RIGHTPADDING', (0, 0), (-1, -1), 8),
		('GRID', (0, 0), (-1, -1), 0.5, line_color),
		('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_color])
	]))
	story.append(summary_table)
	story.append(Spacer(1, 15))

	# ----------------------------------------------------
	# 3. Content Preview
	# ----------------------------------------------------
	story.append(Paragraph("Content Preview", section_heading_style))
	story.append(Spacer(1, 6))
	preview_text = clean_text[:1000]
	if len(clean_text) > 1000:
		preview_text += "..."
	story.append(Paragraph(escape(preview_text).replace("\n", "<br/>"), body_style))
	story.append(Spacer(1, 15))

	# ----------------------------------------------------
	# 4. Headings
	# ----------------------------------------------------
	story.append(Paragraph("Headings List", section_heading_style))
	story.append(Spacer(1, 6))
	if headings:
		for heading in headings[:20]:
			story.append(Paragraph(f"• {escape(heading)}", bullet_style))
	else:
		story.append(Paragraph("No headings available.", body_style))
	story.append(Spacer(1, 15))

	# ----------------------------------------------------
	# 5. Tables
	# ----------------------------------------------------
	if tables:
		story.append(Paragraph("Extracted Tables", section_heading_style))
		
		for idx, table_data in enumerate(tables[:5], start=1):
			# Spacer and table title header
			story.append(Spacer(1, 12))
			story.append(Paragraph(f"<b>Table {idx}:</b>", styles["Heading3"]))
			story.append(Spacer(1, 6))

			formatted_rows = []
			for r_idx, row in enumerate(table_data):
				if not isinstance(row, list):
					continue
				formatted_row = []
				for cell in row:
					text_str = str(cell or "").strip()
					if len(text_str) > 200:
						text_str = text_str[:197] + "..."
					cell_text = escape(text_str)
					style = header_cell_style if r_idx == 0 else cell_style
					formatted_row.append(Paragraph(cell_text, style))
				if formatted_row:
					formatted_rows.append(formatted_row)

			if not formatted_rows:
				continue

			try:
				# 1. Pad rows to raw_max_cols first so we can analyze columns
				raw_max_cols = max(len(row) for row in formatted_rows)
				padded_rows = []
				for row in formatted_rows:
					padded_row = list(row)
					while len(padded_row) < raw_max_cols:
						padded_row.append(Paragraph("", cell_style))
					padded_rows.append(padded_row)

				# 2. Find columns that are not completely empty across all rows
				active_col_indices = []
				for col_idx in range(raw_max_cols):
					col_has_content = False
					for row in padded_rows:
						cell_text = row[col_idx].text.strip()
						if cell_text:
							col_has_content = True
							break
					if col_has_content:
						active_col_indices.append(col_idx)

				# 3. Limit to at most 8 active columns to ensure readability in portrait PDF
				active_col_indices = active_col_indices[:8]

				if not active_col_indices:
					continue

				# 4. Reconstruct rows keeping only active columns
				final_rows = []
				for row in padded_rows:
					final_row = [row[idx] for idx in active_col_indices]
					final_rows.append(final_row)

				max_cols = len(active_col_indices)
				col_width = 504.0 / max_cols if max_cols > 0 else 100.0
				
				t = LongTable(final_rows, colWidths=[col_width] * max_cols, repeatRows=1)
				t.setStyle(TableStyle([
					('BACKGROUND', (0, 0), (-1, 0), primary_color),
					('ALIGN', (0, 0), (-1, -1), 'LEFT'),
					('VALIGN', (0, 0), (-1, -1), 'TOP'),
					('BOTTOMPADDING', (0, 0), (-1, -1), 4),
					('TOPPADDING', (0, 0), (-1, -1), 4),
					('LEFTPADDING', (0, 0), (-1, -1), 4),
					('RIGHTPADDING', (0, 0), (-1, -1), 4),
					('GRID', (0, 0), (-1, -1), 0.5, line_color),
					('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_color]),
				]))
				story.append(t)
			except Exception as table_err:
				print(f"Warning: Failed to render table {idx}: {table_err}")
				story.append(Paragraph("Failed to render table layout.", body_style))

	# Build PDF with page footers
	try:
		doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
		print("PDF report generated")
	except Exception as error:
		print(f"Failed to generate PDF report: {error}")
		raise error