from datetime import datetime
from typing import Any, Dict
from xml.sax.saxutils import escape

from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, LongTable, PageBreak
from reportlab.lib import colors

try:
	from backend.ai import AIAnalyzer
except ImportError:
	try:
		from ai import AIAnalyzer
	except ImportError:
		AIAnalyzer = None


def add_footer(canvas, doc):
	"""Canvas callback to draw a clean footer on all pages."""
	canvas.saveState()
	canvas.setFont('Helvetica', 8)
	canvas.setFillColor(colors.HexColor("#4f5b70"))
	
	# Draw divider line above footer
	canvas.setStrokeColor(colors.HexColor("#eadcc8"))
	canvas.setLineWidth(0.5)
	canvas.line(54, 45, 558, 45)
	
	# Draw footer labels
	canvas.drawString(54, 30, "Generated by ScrapeX")
	canvas.drawRightString(558, 30, f"Page {doc.page}")
	canvas.restoreState()


def calculate_col_widths(rows, max_total_width=504.0, max_col_width=180.0, min_col_width=35.0) -> list:
	"""Calculate column widths dynamically based on cell content length.
	
	Estimates the width of each column by finding the maximum text length,
	capping each column at max_col_width, and scaling down proportionally
	if the total width exceeds max_total_width.
	"""
	if not rows:
		return []
		
	num_cols = len(rows[0])
	col_widths = [min_col_width] * num_cols
	
	for row in rows:
		for col_idx, cell in enumerate(row):
			if col_idx >= num_cols:
				continue
			# cell is a Paragraph, so we extract its text
			text_str = cell.text if hasattr(cell, "text") else ""
			# Estimate character width: ~5.5 points per character for small font size (8)
			est_width = max(len(text_str) * 5.5, min_col_width)
			if est_width > col_widths[col_idx]:
				col_widths[col_idx] = est_width

	# Apply max column width constraint
	col_widths = [min(w, max_col_width) for w in col_widths]
	
	# Scale down to fit total page width if necessary
	total_width = sum(col_widths)
	if total_width > max_total_width:
		scale = max_total_width / total_width
		col_widths = [max(w * scale, min_col_width) for w in col_widths]
		
	return col_widths


def export_to_pdf(data: Dict[str, Any], filename: str = "report.pdf") -> None:
	"""Generate a clean, professional PDF report from scraped website data with AI analysis.

	Args:
		data: Scraped data dictionary containing values such as title, url,
			clean_text, headings, and optional ai_analysis.
		filename: Output PDF filename.
	"""
	# Document layout configuration (margins set to 54pt / 0.75 in)
	doc = SimpleDocTemplate(
		filename,
		leftMargin=54,
		rightMargin=54,
		topMargin=54,
		bottomMargin=54
	)
	story = []

	# Raw data extraction
	title = str(data.get("title") or "No Title")
	url = str(data.get("url") or "")
	clean_text = str(data.get("clean_text") or "No content available")

	raw_headings = data.get("headings")
	if isinstance(raw_headings, list):
		headings = [str(item) for item in raw_headings if item]
	else:
		headings = []

	raw_tables = data.get("tables")
	if isinstance(raw_tables, list):
		tables = [item for item in raw_tables if isinstance(item, list) and item]
	else:
		tables = []

	# Style Definitions
	styles = getSampleStyleSheet()
	
	# Cohesive design palette variables
	primary_color = colors.HexColor("#0f9d8b")   # Teal
	secondary_color = colors.HexColor("#2f71d8") # Blue
	text_color = colors.HexColor("#1a2333")      # Ink
	muted_color = colors.HexColor("#4f5b70")     # Muted Ink
	bg_color = colors.HexColor("#fffdf7")        # Sand / Paper background
	line_color = colors.HexColor("#eadcc8")      # Border sand-gold line

	title_style = ParagraphStyle(
		'ReportTitle',
		parent=styles['Heading1'],
		fontName='Helvetica-Bold',
		fontSize=22,
		leading=26,
		textColor=primary_color,
		spaceAfter=6
	)
	
	meta_label_style = ParagraphStyle(
		'MetaLabel',
		parent=styles['Normal'],
		fontName='Helvetica-Bold',
		fontSize=9,
		leading=13,
		textColor=text_color
	)

	meta_value_style = ParagraphStyle(
		'MetaValue',
		parent=styles['Normal'],
		fontName='Helvetica',
		fontSize=9,
		leading=13,
		textColor=muted_color
	)

	section_heading_style = ParagraphStyle(
		'SectionHeading',
		parent=styles['Heading2'],
		fontName='Helvetica-Bold',
		fontSize=13,
		leading=17,
		textColor=secondary_color,
		spaceBefore=12,
		spaceAfter=6,
		keepWithNext=True
	)

	body_style = ParagraphStyle(
		'ReportBodyText',
		parent=styles['Normal'],
		fontName='Helvetica',
		fontSize=9,
		leading=14,
		textColor=text_color,
		spaceAfter=6
	)

	bullet_style = ParagraphStyle(
		'ReportBulletText',
		parent=styles['Normal'],
		fontName='Helvetica',
		fontSize=9,
		leading=13,
		textColor=text_color,
		leftIndent=15,
		firstLineIndent=-10,
		spaceAfter=4
	)

	cell_style = ParagraphStyle(
		'TableCellStyle',
		parent=styles['Normal'],
		fontSize=8,
		leading=10,
		textColor=text_color
	)

	header_cell_style = ParagraphStyle(
		'TableHeaderStyle',
		parent=styles['Normal'],
		fontSize=8,
		leading=10,
		textColor=colors.whitesmoke,
		fontName='Helvetica-Bold'
	)

	# ----------------------------------------------------
	# 1. Cover Header
	# ----------------------------------------------------
	story.append(Paragraph("ScrapeX Web Scraper Report", title_style))
	story.append(Spacer(1, 8))

	now = datetime.now()
	date_str = now.strftime("%Y-%m-%d")
	time_str = now.strftime("%H:%M:%S")
	scrape_method = str(data.get("scrape_method") or "Unknown")

	meta_data = [
		[Paragraph("Website Title:", meta_label_style), Paragraph(escape(title), meta_value_style)],
		[Paragraph("Source URL:", meta_label_style), Paragraph(escape(url), meta_value_style)],
		[Paragraph("Generated Date:", meta_label_style), Paragraph(date_str, meta_value_style)],
		[Paragraph("Generated Time:", meta_label_style), Paragraph(time_str, meta_value_style)],
		[Paragraph("Scrape Method:", meta_label_style), Paragraph(scrape_method, meta_value_style)]
	]
	
	meta_table = Table(meta_data, colWidths=[110, 394])
	meta_table.setStyle(TableStyle([
		('VALIGN', (0, 0), (-1, -1), 'TOP'),
		('BOTTOMPADDING', (0, 0), (-1, -1), 3),
		('TOPPADDING', (0, 0), (-1, -1), 3),
	]))
	story.append(meta_table)
	
	# Divider line
	divider = Table([[""]], colWidths=[504])
	divider.setStyle(TableStyle([
		('LINEBELOW', (0, 0), (-1, -1), 1, primary_color),
		('BOTTOMPADDING', (0, 0), (-1, -1), 6),
		('TOPPADDING', (0, 0), (-1, -1), 6),
	]))
	story.append(divider)
	story.append(Spacer(1, 8))

	# ----------------------------------------------------
	# 2. AI Architectural Analysis Section
	# ----------------------------------------------------
	ai_info = data.get("ai_analysis")
	if not ai_info and AIAnalyzer:
		try:
			ai_info = AIAnalyzer().analyze_page(clean_text[:5000], url).to_dict()
		except Exception as exc:
			print(f"Warning: PDF export fallback AI analysis failed: {exc}")
			ai_info = None

	if ai_info and isinstance(ai_info, dict):
		story.append(Paragraph("AI Architectural Analysis", section_heading_style))
		story.append(Spacer(1, 4))

		website_type_str = escape(str(ai_info.get("website_type") or "Unknown"))
		framework_str = escape(str(ai_info.get("framework") or "Unknown"))
		content_conf_val = float(ai_info.get("content_confidence") or 0.0)
		table_conf_val = float(ai_info.get("table_confidence") or 0.0)
		content_conf_str = f"{int(content_conf_val * 100)}%"
		table_conf_str = f"{int(table_conf_val * 100)}%"
		req_js_str = "Yes" if ai_info.get("requires_javascript") else "No"
		rec_strat_str = escape(str(ai_info.get("recommended_strategy") or ai_info.get("scrape_strategy") or "Standard HTML"))
		summary_text = escape(str(ai_info.get("summary") or "No architectural summary provided."))

		ai_table_data = [
			[Paragraph("<b>Metric / Indicator</b>", meta_label_style), Paragraph("<b>AI Evaluation Result</b>", meta_label_style)],
			[Paragraph("Website Type", body_style), Paragraph(website_type_str, body_style)],
			[Paragraph("Detected Framework", body_style), Paragraph(framework_str, body_style)],
			[Paragraph("Content Confidence", body_style), Paragraph(content_conf_str, body_style)],
			[Paragraph("Table Confidence", body_style), Paragraph(table_conf_str, body_style)],
			[Paragraph("Requires JavaScript", body_style), Paragraph(req_js_str, body_style)],
			[Paragraph("Recommended Strategy", body_style), Paragraph(f"<b>{rec_strat_str}</b>", body_style)],
			[Paragraph("Architectural Summary", body_style), Paragraph(summary_text, body_style)]
		]

		raw_warnings = ai_info.get("warnings") or []
		if raw_warnings:
			warnings_formatted = "<br/>".join([f"• {escape(str(w))}" for w in raw_warnings])
			ai_table_data.append([Paragraph("AI Warnings & Hazards", body_style), Paragraph(warnings_formatted, body_style)])
		else:
			ai_table_data.append([Paragraph("AI Warnings & Hazards", body_style), Paragraph("None detected.", body_style)])

		ai_table = Table(ai_table_data, colWidths=[180, 324])
		ai_table.setStyle(TableStyle([
			('BACKGROUND', (0, 0), (-1, 0), line_color),
			('VALIGN', (0, 0), (-1, -1), 'TOP'),
			('BOTTOMPADDING', (0, 0), (-1, -1), 4),
			('TOPPADDING', (0, 0), (-1, -1), 4),
			('LEFTPADDING', (0, 0), (-1, -1), 8),
			('RIGHTPADDING', (0, 0), (-1, -1), 8),
			('GRID', (0, 0), (-1, -1), 0.5, line_color),
			('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_color])
		]))
		story.append(ai_table)
		story.append(Spacer(1, 10))

	# ----------------------------------------------------
	# 3. Summary Statistics
	# ----------------------------------------------------
	story.append(Paragraph("Summary Statistics", section_heading_style))
	story.append(Spacer(1, 4))

	summary_data = [
		[Paragraph("<b>Statistic</b>", meta_label_style), Paragraph("<b>Value</b>", meta_label_style)],
		[Paragraph("Total Content Length (characters)", body_style), Paragraph(str(len(clean_text)), body_style)],
		[Paragraph("Number of Headings", body_style), Paragraph(str(len(headings)), body_style)],
		[Paragraph("Number of Paragraphs", body_style), Paragraph(str(len(data.get("paragraphs") or [])), body_style)],
		[Paragraph("Number of Links", body_style), Paragraph(str(len(data.get("links") or [])), body_style)],
		[Paragraph("Number of Tables", body_style), Paragraph(str(len(tables)), body_style)]
	]
	summary_table = Table(summary_data, colWidths=[252, 252])
	summary_table.setStyle(TableStyle([
		('BACKGROUND', (0, 0), (-1, 0), line_color),
		('VALIGN', (0, 0), (-1, -1), 'TOP'),
		('BOTTOMPADDING', (0, 0), (-1, -1), 4),
		('TOPPADDING', (0, 0), (-1, -1), 4),
		('LEFTPADDING', (0, 0), (-1, -1), 8),
		('RIGHTPADDING', (0, 0), (-1, -1), 8),
		('GRID', (0, 0), (-1, -1), 0.5, line_color),
		('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_color])
	]))
	story.append(summary_table)
	
	# Dedicated report summary cover page (push preview and tables to page 2+)
	story.append(PageBreak())

	# ----------------------------------------------------
	# 4. Content Preview
	# ----------------------------------------------------
	story.append(Paragraph("Content Preview", section_heading_style))
	story.append(Spacer(1, 6))
	preview_text = clean_text[:1000]
	if len(clean_text) > 1000:
		preview_text += "..."
	story.append(Paragraph(escape(preview_text).replace("\n", "<br/>"), body_style))
	story.append(Spacer(1, 15))

	# ----------------------------------------------------
	# 5. Headings
	# ----------------------------------------------------
	story.append(Paragraph("Headings List", section_heading_style))
	story.append(Spacer(1, 6))
	if headings:
		for heading in headings[:20]:
			story.append(Paragraph(f"• {escape(heading)}", bullet_style))
	else:
		story.append(Paragraph("No headings available.", body_style))
	story.append(Spacer(1, 15))

	# ----------------------------------------------------
	# 6. Tables
	# ----------------------------------------------------
	if tables:
		story.append(Paragraph("Extracted Tables", section_heading_style))
		
		for idx, table_data in enumerate(tables[:5], start=1):
			formatted_rows = []
			for r_idx, row in enumerate(table_data):
				if not isinstance(row, list):
					continue
				
				# Skip completely empty rows
				is_empty_row = all(not str(cell or "").strip() for cell in row)
				if is_empty_row:
					continue

				formatted_row = []
				for cell in row:
					text_str = str(cell or "").strip()
					if len(text_str) > 200:
						text_str = text_str[:197] + "..."
					cell_text = escape(text_str)
					style = header_cell_style if r_idx == 0 else cell_style
					formatted_row.append(Paragraph(cell_text, style))
				if formatted_row:
					formatted_rows.append(formatted_row)

			if not formatted_rows:
				continue

			try:
				raw_max_cols = max(len(row) for row in formatted_rows)
				padded_rows = []
				for row in formatted_rows:
					padded_row = list(row)
					while len(padded_row) < raw_max_cols:
						padded_row.append(Paragraph("", cell_style))
					padded_rows.append(padded_row)

				active_col_indices = []
				for col_idx in range(raw_max_cols):
					col_has_content = False
					for row in padded_rows:
						cell_text = row[col_idx].text.strip()
						if cell_text:
							col_has_content = True
							break
					if col_has_content:
						active_col_indices.append(col_idx)

				active_col_indices = active_col_indices[:8]

				if not active_col_indices:
					continue

				final_rows = []
				for row in padded_rows:
					final_row = [row[idx] for idx in active_col_indices]
					final_rows.append(final_row)

				max_cols = len(active_col_indices)

				span_commands = []
				for r_idx, row in enumerate(final_rows):
					non_empty_indices = [c_idx for c_idx, cell in enumerate(row) if cell.text.strip()]
					if len(non_empty_indices) == 1 and non_empty_indices[0] == 0:
						span_commands.append(('SPAN', (0, r_idx), (max_cols - 1, r_idx)))

				if idx > 1:
					if len(final_rows) > 10:
						story.append(PageBreak())
					else:
						story.append(Spacer(1, 15))

				story.append(Paragraph(f"<b>Table {idx}:</b>", styles["Heading3"]))
				story.append(Spacer(1, 6))

				col_widths = calculate_col_widths(final_rows)
				
				t = LongTable(final_rows, colWidths=col_widths, repeatRows=1, hAlign='CENTER')
				t_style_list = [
					('BACKGROUND', (0, 0), (-1, 0), primary_color),
					('ALIGN', (0, 0), (-1, -1), 'LEFT'),
					('VALIGN', (0, 0), (-1, -1), 'TOP'),
					('LEFTPADDING', (0, 0), (-1, -1), 8),
					('RIGHTPADDING', (0, 0), (-1, -1), 8),
					('TOPPADDING', (0, 0), (-1, -1), 6),
					('BOTTOMPADDING', (0, 0), (-1, -1), 6),
					('GRID', (0, 0), (-1, -1), 0.5, line_color),
					('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafd")]),
				]
				t_style_list.extend(span_commands)
				t.setStyle(TableStyle(t_style_list))
				story.append(t)
			except Exception as table_err:
				print(f"Warning: Failed to render table {idx}: {table_err}")
				story.append(Paragraph("Failed to render table layout.", body_style))

	# Build PDF with page footers
	try:
		doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
		print("PDF report generated")
	except Exception as error:
		print(f"Failed to generate PDF report: {error}")
		raise error